### ISSUE TITLE
[BUG] Missing "Filmek"

### ISSUE THREAD

**Issue by pgillich** [billsuxx/plugin.video.hbogohu#17]
Hi,

The list of movies in "Filmek" is disappeared in the last few weeks. It worked earlier, so it's a different issue to #13

Environment:
RPi3, Kodi 18.2, LibreELEC 9.0.2, HBO GO Hungary 0.2.3

Symptomes:
When I selected the "Filmek" or the "Keresés...", I got "HBO GO Hungary error" message, instead of getting a list of movies.
Other items, for example: "Lejátszási listád", "Ajánlataink", "Kedvenceim", "Előzmények" work.

Log items from :~/.kodi/temp/kodi.log:

```

2020-03-21 09:09:04.005 T:1497408368   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.hbogohu/addon.py", line 577, in <module>
                                                LIST(url)
                                              File "/storage/.kodi/addons/plugin.video.hbogohu/addon.py", line 286, in LIST
                                                for titles in range(0, len(jsonrsp['Container'][0]['Contents']['Items'])):
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
2020-03-21 09:09:04.180 T:1489015664   ERROR: GetDirectory - Error getting plugin://plugin.video.hbogohu/?mode=1&name=Filmek&url=https%3a%2f%2fhuapi.hbogo.eu%2fv5%2fGroup%2fjson%2fHUN%2fCOMP%2fb84a7a5f-ff13-4854-956b-9bc1070457f1%2f0%2f0%2f0%2f0%2f0%2f0
2020-03-21 09:09:04.182 T:1937416208   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.hbogohu/?mode=1&name=Filmek&url=https%3a%2f%2fhuapi.hbogo.eu%2fv5%2fGroup%2fjson%2fHUN%2fCOMP%2fb84a7a5f-ff13-4854-956b-9bc1070457f1%2f0%2f0%2f0%2f0%2f0%2f0) failed
2020-03-21 09:12:46.256 T:1790935920   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'encode'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.hbogohu/addon.py", line 586, in <module>
                                                SEARCH()
                                              File "/storage/.kodi/addons/plugin.video.hbogohu/addon.py", line 495, in SEARCH
                                                addDir(jsonrsp['Container'][0]['Contents']['Items'][index]['Name'].encode('utf-8', 'ignore'),jsonrsp['Container'][0]['Contents']['Items'][index]['ObjectUrl'],jsonrsp['Container'][0]['Contents']['Items'][index]['Abstract'].encode('utf-8', 'ignore'),2,jsonrsp['Container'][0]['Contents']['Items'][index]['BackgroundUrl'])
                                            AttributeError: 'NoneType' object has no attribute 'encode'
                                            -->End of Python script error report<--
2020-03-21 09:12:46.469 T:1799328624   ERROR: GetDirectory - Error getting plugin://plugin.video.hbogohu/?mode=4&name=Keres%c3%a9s...&url=search
2020-03-21 09:12:46.472 T:1937416208   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.hbogohu/?mode=4&name=Keres%c3%a9s...&url=search) failed
```

**Comment by gerelorant** [comment]
Same here.

Also 'Sorozatok' don't even show up in the options.

I tried deleting the addon and installing it again, with no help.

**Comment by gerelorant** [comment]
I thinks the problem might be the change in the operator id of UPC Magyarország (now Vodafone Hungary). If someone could update the operator list, it would be much appreciated!

**Comment by pgillich** [comment]
My provider is: "HBO GO webes"

**Comment by AtexPatex** [comment]
HBO seems to have changed something in the API. The category query does not return Series ("Sorozatok") at all and returns empty Movies ("Filmek") category.

**Comment by schneci** [comment]
Hi,

I think the problem is the LIST(url) function is getted wrong url:
`https://huapi.hbogo.eu/v5/Group/json/HUN/COMP/b84a7a5f-ff13-4854-956b-9bc1070457f1/0/0/0/0/0/0`

In browser this link shows next json message: 
```json
{
ObjectType: 3,
Success: false,
Color: null,
Container: [ ],
ExpiryMin: 0,
Filters: [ ],
Host: "AZWM1CLW14",
Id: "00000000-0000-0000-0000-000000000000",
Index: 0,
IsSelection: false,
Name: null,
SelectionIndex: 0,
ShowInMenu: false,
SortOptions: [ ],
Tracking: null,
ViewType: 0
}
``` 

This is why the following error message occurs in visual code:

`Exception has occurred: KeyError
('Container',)
  File "c:\users\sgy\appdata\roaming\kodi\addons\plugin.video.hbogohu\addon.py", line 428, in LIST
    if len(jsonrsp['Container']) > 1:
  File "c:\users\sgy\appdata\roaming\kodi\addons\plugin.video.hbogohu\addon.py", line 850, in main
    LIST(url)
  File "c:\users\sgy\appdata\roaming\kodi\addons\plugin.video.hbogohu\addon.py", line 885, in <module>
    main()`
