### ISSUE TITLE
Addon not working on Raspberry Pi 3

### ISSUE THREAD

**Issue by hahnrobi** [billsuxx/plugin.video.hbogohu#18]
When opening the app and selecting a menu item, the following error appears in the log.
version, status, reason = self._read_status()
                                              File "/usr/lib/python2.7/httplib.py", line 412, in _read_status
                                                raise BadStatusLine("No status line received - the server has closed the connection")
                                            BadStatusLine: No status line received - the server has closed the connection
                                            -->End of Python script error report<--
2020-07-13 15:18:12.121 T:2481950944   ERROR: GetDirectory - Error getting plugin://plugin.video.hbogohu/?mode=1&name=Lej%c3%a1tsz%c3%a1si%20list%c3%a1d&url=https%3a%2f%2fhuapi.hbogo.eu%2fv7%2fCustomerGroup%2fjson%2fHUN%2fCOMP%2fda4abef8-4b5c-4d83-a941-a0e4771c9837%2f-%2f-%2f-%2f1000%2f-%2f-%2ffalse
2020-07-13 15:18:12.122 T:2984270912   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.hbogohu/?mode=1&name=Lej%c3%a1tsz%c3%a1si%20list%c3%a1d&url=https%3a%2f%2fhuapi.hbogo.eu%2fv7%2fCustomerGroup%2fjson%2fHUN%2fCOMP%2fda4abef8-4b5c-4d83-a941-a0e4771c9837%2f-%2f-%2f-%2f1000%2f-%2f-%2ffalse) failed
2020-07-13 15:18:21.564 T:2984270912 WARNING: CGUIWindowManager - HandleAction - ignoring action 107, because topmost modal dialog closing animation is running
2020-07-13 15:18:46.578 T:2984270912 WARNING: Previous line repeats 27 times.
2020-07-13 15:18:46.578 T:2984270912   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
2020-07-13 15:20:17.530 T:2490343648   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'httplib.BadStatusLine'>
                                            Error Contents: No status line received - the server has closed the connection
                                            Traceback (most recent call last):
                                              File "/home/xbian/.kodi/addons/plugin.video.hbogohu/addon.py", line 577, in <module>
                                                LIST(url)
                                              File "/home/xbian/.kodi/addons/plugin.video.hbogohu/addon.py", line 269, in LIST
                                                LOGIN()
                                              File "/home/xbian/.kodi/addons/plugin.video.hbogohu/addon.py", line 179, in LOGIN
                                                jsonrsp = SILENTREGISTER()
                                              File "/home/xbian/.kodi/addons/plugin.video.hbogohu/addon.py", line 135, in SILENTREGISTER
                                                f = opener.open(req)
                                              File "/usr/lib/python2.7/urllib2.py", line 429, in open
                                                response = self._open(req, data)
                                              File "/usr/lib/python2.7/urllib2.py", line 447, in _open
                                                '_open', req)
                                              File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
                                                result = func(*args)
                                              File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
                                                context=self._context)
                                              File "/usr/lib/python2.7/urllib2.py", line 1201, in do_open
                                                r = h.getresponse(buffering=True)
                                              File "/usr/lib/python2.7/httplib.py", line 1137, in getresponse
                                                response.begin()
                                              File "/usr/lib/python2.7/httplib.py", line 448, in begin
                                                version, status, reason = self._read_status()
                                              File "/usr/lib/python2.7/httplib.py", line 412, in _read_status
                                                raise BadStatusLine("No status line received - the server has closed the connection")
                                            BadStatusLine: No status line received - the server has closed the connection
                                            -->End of Python script error report<--
2020-07-13 15:20:17.693 T:2465165536   ERROR: GetDirectory - Error getting plugin://plugin.video.hbogohu/?mode=1&name=Aj%c3%a1nlataink&url=https%3a%2f%2fhuapi.hbogo.eu%2fv5%2fGroup%2fjson%2fHUN%2fCOMP%2f22c730b8-797a-429d-9c94-0e6b2334782f%2f0%2f0%2f0%2f0%2f0%2f0
2020-07-13 15:20:17.695 T:2984270912   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.hbogohu/?mode=1&name=Aj%c3%a1nlataink&url=https%3a%2f%2fhuapi.hbogo.eu%2fv5%2fGroup%2fjson%2fHUN%2fCOMP%2f22c730b8-797a-429d-9c94-0e6b2334782f%2f0%2f0%2f0%2f0%2f0%2f0) failed

**Comment by esajosi** [comment]
I think I have the same problem.
I use invitel subscription, maybe this is a problem?

**Comment by TedBaron** [comment]
@hahnrobi, @billsuxx 
Boldog karácsonyt!!!!
Lett ennek megoldása július óta?
szintén ezzel a problémával szembesültem.

**Comment by esajosi** [comment]
Nos...vagy 500x probaltam belepni, plusz megprobaltam pythonban
vegigcsinalni (konzolbol) amit ez a cucc csinal, parhuzamosan az hbo go eu
nevu pluginnel, az utobbi egyszercsak elindult.
Hogy ez most a tobbszor elirt jelszo sikeres beirasa vagy egy komplett kodi
frissites miatt kezdett mukodni?
Allati nehez lenne megallapitani, elment vele vagy 2 hónap.
Az hbo go hu plugin nem mukodik csak ez az ujabb, a programot latva
alaposan ujraszervezett kód...
Ervin

TedBaron <notifications@github.com> ezt írta (időpont: 2020. dec. 25., Pén
21:46):

**Comment by hahnrobi** [comment]
Az hGO EU addon-t használtam helyette néhány hónapig. Az tökéletesen működött, ezzel én akkor feladtam a küszködést, nem tudom azóta megoldódott-e a probléma. Az hGO EU esetleg az megérhet egy próbát, nálam az Pi-n bevált.
Szintén kellemes ünnepeket!
